"use client";
import { useEffect, useMemo, useState } from "react";
import { checkRoutine } from "@/lib/products/routine";
import { hasReactionConsent, loadProducts, loadReactions } from "@/lib/products/store";
import { PRODUCT_TYPES, type Reaction, type SavedProduct } from "@/lib/products/types";
import { loadProfile } from "@/lib/rules/profileStore";
import { EMPTY_PROFILE, type Profile } from "@/lib/rules/types";

export default function ReportClient() {
  const [products, setProducts] = useState<SavedProduct[]>([]), [profile, setProfile] = useState<Profile>(EMPTY_PROFILE), [log, setLog] = useState<Reaction[]>([]), [consent, setConsent] = useState(false);
  useEffect(() => { setProducts(loadProducts()); setProfile(loadProfile()); setLog(loadReactions()); setConsent(hasReactionConsent()); }, []);
  const [sel, setSel] = useState<Record<string, boolean>>({});
  const [inc, setInc] = useState({ routine: true, lists: true, avoid: false, reactions: false, skin: false });
  const chosen = products.filter((p) => sel[p.id]);
  const routine = useMemo(() => (chosen.length ? checkRoutine(chosen) : null), [chosen]);
  const typeLabel = (t: string) => PRODUCT_TYPES.find((x) => x.v === t)?.label ?? "";
  const when = (w: string) => (w === "am" ? "Morning" : w === "pm" ? "Evening" : w === "both" ? "Morning and evening" : "Time not set");
  const box = (k: keyof typeof inc, label: string, disabled = false) => (
    <label style={{ fontWeight: 400 }}><input type="checkbox" disabled={disabled} checked={inc[k] && !disabled} onChange={(e) => setInc({ ...inc, [k]: e.target.checked })} /> {label}</label>);

  return (
    <main>
      <div className="no-print">
        <h1>Doctor-friendly report</h1>
        <p className="notice info" role="note">Built on this device from what you choose below. Nothing is uploaded. Use “Print or save as PDF” in your browser to keep or share it. Only ticked items appear.</p>
        <section className="card" aria-labelledby="w">
          <h2 id="w">What to include</h2>
          {!products.length && <p className="notice warn">No saved products. <a href="/products">Add some first</a>.</p>}
          <ul className="plain">{products.map((p) => <li key={p.id}><label style={{ fontWeight: 400 }}><input type="checkbox" checked={!!sel[p.id]} onChange={(e) => setSel({ ...sel, [p.id]: e.target.checked })} /> {p.name}</label></li>)}</ul>
          {box("routine", "Routine and notes")}{box("lists", "Full ingredient lists")}{box("skin", "Skin type and concerns")}{box("avoid", "My avoid list")}
          {box("reactions", consent ? "Reaction log" : "Reaction log (turn on the log with consent first)", !consent)}
          <button onClick={() => window.print()} disabled={!chosen.length}>Print or save as PDF</button>
        </section>
      </div>

      {chosen.length > 0 && (
        <article aria-label="Report preview">
          <h1 className="sr-only">Report</h1>
          <h2>BeautyLens summary · {new Date().toLocaleDateString()}</h2>
          <p><small>Generated by the person using this tool from a label-reading app. Ingredient names were identified by software and may contain errors. This is not a diagnosis or medical record.</small></p>
          {inc.skin && <section className="card"><h3>Skin</h3><p>Type: {profile.skinType || "not set"}. Concerns: {profile.concerns.join(", ") || "none listed"}.{profile.pregnant ? " Pregnant." : ""}{profile.breastfeeding ? " Breastfeeding." : ""}</p></section>}
          {inc.routine && routine && (
            <section className="card"><h3>Routine</h3>
              <table className="cmp"><thead><tr><th>Product</th><th>Type</th><th>Used</th></tr></thead><tbody>{chosen.map((p) => <tr key={p.id}><td>{p.name}</td><td>{typeLabel(p.type) || "—"}</td><td>{when(p.when)}</td></tr>)}</tbody></table>
              {routine.notes.length > 0 && <><h4>Notes (from sourced rules)</h4><ul>{routine.notes.map((n, i) => <li key={i}><strong>{n.title}.</strong> {n.text} {n.source.length > 0 && <small>(Sources: {n.source.map((s) => `${s.label} ${s.url}`).join("; ")})</small>}</li>)}</ul></>}
            </section>)}
          {inc.lists && (
            <section className="card"><h3>Ingredient lists</h3>
              {chosen.map((p) => (<div key={p.id}><h4>{p.name}</h4>
                <p><strong>Identified</strong> (names matched to the EU glossary of common ingredient names or user-confirmed): {p.ingredients.join(", ") || "none"}.</p>
                {p.unresolved.length > 0 && <p><strong>Not confirmed</strong> (as printed): {p.unresolved.join(", ")}.</p>}</div>))}
              <p><small>Printed order is kept. Order does not show concentration.</small></p>
            </section>)}
          {inc.avoid && <section className="card"><h3>Avoid list</h3>{profile.avoid.length ? <ul>{profile.avoid.map((e) => <li key={e.id}>{e.label} · {e.strength === "doctor" ? "doctor-confirmed" : "personal preference"}</li>)}</ul> : <p>Empty.</p>}</section>}
          {inc.reactions && consent && (
            <section className="card"><h3>Reaction log</h3>{log.length ? <ul>{log.map((r) => <li key={r.id}>{products.find((p) => p.id === r.productId)?.name ?? "(removed product)"}{r.date ? `, ${r.date}` : ""}{r.note ? `: ${r.note}` : ""}</li>)}</ul> : <p>Nothing logged.</p>}
              <p><small>Self-reported. It does not show what caused a reaction.</small></p></section>)}
        </article>)}
    </main>
  );
}
